[package]
name = "blog-builder"
version = "0.1.0"
authors = ["Todd Kennedy <todd@selfassembled.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
chrono = "0.4"
comrak = "0.10.0"
voca_rs = "1.13.0"
handlebars = "3.5.3"
serde_json = "1.0.59"
